tmux:
    symbols:
        branch: ""
        hashprefix: ":"
        ahead: "↑"
        behind: "↓"
        staged: "●"
        conflict: "✖"
        modified: "+"
        untracked: "?"
        stashed: "⚑"
        clean: "✔"

    styles:
        clear: "#[none]"
        state: "#[fg=#fb4934,bold]"
        branch: "#[fg=#8ec07c,bold]"
        remote: "#[fg=#83a598]"
        divergence: "#[fg=#fabd2f]"
        staged: "#[fg=#b8bb26,bold]"
        conflict: "#[fg=#fb4934,bold]"
        modified: "#[fg=#fe8019,bold]"
        untracked: "#[fg=#d3869b]"
        stashed: "#[fg=#83a598]"
        clean: "#[fg=#b8bb26,bold]"

    layout: [branch, divergence, " ", flags]

    options:
        branch_max_len: 20
        branch_trim: right
        ellipsis: …
        hide_clean: false
        swap_divergence: false
        divergence_space: false
        flags_without_count: false
